final for 2day sanity

diff --git a/wazuh-setup-docker/docker-compose.yml b/wazuh-setup-docker/docker-compose.yml
--- a/wazuh-setup-docker/docker-compose.yml
+++ b/wazuh-setup-docker/docker-compose.yml
@@ -72,9 +72,6 @@ services:
       - wazuh-manager-active-response:/var/ossec/active-response/bin
       - wazuh-manager-agentless:/var/ossec/agentless
       - wazuh-manager-wodles:/var/ossec/wodles
-      - ./wazuh_manager/ossec.conf:/wazuh-config-mount/etc/ossec/ossec.conf
-      - ./wazuh_manager/local_rules.xml:/var/ossec/etc/rules/local_rules.xml
-      - ./wazuh_manager/local_decoders.xml:/var/ossec/etc/decoders/local_decoders.xml
     depends_on:
       - wazuh-elasticsearch
     networks:
@@ -100,20 +97,19 @@ services:
     networks:
       - wazuh
 
-  # Log generator for testing (generates sample security events)
+  # Log generator for testing (sends syslog lines to Wazuh Manager via UDP 514)
   log-generator:
-    image: mingrammer/flog
+    image: alpine:3.20
     container_name: wazuh-log-generator
     restart: always
     command: >
       sh -c "
+      apk add --no-cache netcat-openbsd >/dev/null 2>&1 || true;
       while true; do
-        flog -t log -f apache_common -n 5 -d 1 -l | logger -t apache;
-        flog -t log -f apache_error -n 3 -d 1 -l | logger -t apache_error;
-        echo '$(date) sshd[$$]: Failed password for invalid user admin from 192.168.1.100 port 22 ssh2' | logger -t sshd;
-        echo '$(date) kernel: [UFW BLOCK] IN=eth0 OUT= MAC= SRC=192.168.1.200 DST=192.168.1.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=12345 DF PROTO=TCP SPT=45678 DPT=80 WINDOW=29200 RES=0x00 SYN URGP=0' | logger -t kernel;
-        echo '$(date) systemd[1]: Failed to start some critical service' | logger -t systemd;
-        sleep 30;
+        echo \"$(date) sshd[1234]: Failed password for invalid user admin from 192.168.1.100 port 22 ssh2\" | nc -u -w0 wazuh-manager 514;
+        echo \"$(date) kernel: [UFW BLOCK] IN=eth0 OUT= MAC= SRC=192.168.1.200 DST=192.168.1.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=12345 DF PROTO=TCP SPT=45678 DPT=80 WINDOW=29200 RES=0x00 SYN URGP=0\" | nc -u -w0 wazuh-manager 514;
+        echo \"$(date) systemd[1]: Failed to start some critical service\" | nc -u -w0 wazuh-manager 514;
+        sleep 15;
       done
       "
     depends_on:
